
```{r}
##load packages

rm(list = ls())
library(vctrs)
library(ggplot2)
library(purrr)
library(kableExtra)
library(reshape2)
library(stringr)
library(magrittr)
library(randomForest)
library(knitr)
library(seqinr)
library(metagMisc)
library(gridExtra)
library(vegan)
library(plotly)
library(dplyr)
library(indicspecies)
library(yhat)
library("dunn.test"); packageVersion("dunn.test")
library(tidyverse)
library(devtools)
library(BiocParallel)
library(matrixStats)
library(MatrixGenerics)
library(DelayedArray)
library(RSQLite)
library(Biostrings)
library(DESeq2)
library(genefilter)
library(phyloseq)
```


```{r}
ps <- readRDS("C:\\Users\\vmgly\\Documents\\Markergene\\CBASS\\16S\\geno_18Oct2022\\symITSps_16S_CBASS_18Oct2022.rds")
```

```{r}

##Ensure sample data well-merged
sample_data(ps)
```

```{r}
otu <- otu_table(ps)
##tre <- phy_tree(ps)
sam <- sample_data(ps)
tax <- tax_table(ps)
```

```{r}
##Further tax exploration
table(tax_table(ps)[, "Kingdom"], exclude = NULL)

table(tax_table(ps)[, "Phylum"], exclude = NULL)

table(tax_table(ps)[, "Class"], exclude = NULL)

table(tax_table(ps)[, "Order"], exclude = NULL)

table(tax_table(ps)[, "Genus"], exclude = NULL)

table(tax_table(ps)[, "Species"], exclude = NULL)

```


```{r}
###set random seed downstream st

set.seed(100)
``` 

```{r}
## rarecurve(otu, step = 100, col = "blue", 
          ##cex = 0.6,
          ## main = "Rarefaction curve, 16S amplicon")
```

```{r}
##Inspect library sizes

df <- as.data.frame(sample_data(ps)) # Put sample_data into a ggplot-friendly data.frame
df$LibrarySize <- sample_sums(ps)
df <- df[order(df$LibrarySize),]
df$Index <- seq(nrow(df))
ggplot(data=df, aes(x=Index, y=LibrarySize, color=type)) + geom_point()

```

```{r}
sample_data(ps)
```

```{r}
ps

ps <- prune_taxa(taxa_sums(ps) > 0, ps)
any(taxa_sums(ps) == 0)

##Remove all ctrl samples

##library("microbiome")


##ps_c <- remove_samples(c("16S-PlA-E5","16S-PlA-E6","16S-PlA-E7","16S-PlA-E8","16S-PlB-E7","16S-PlB-E8","16S-PlC-E7","16S-PlC-E8","16S-PlD-E8","16S-PlA-H12","16S-PlB-H12","16S-PlC-H12","16S-PlD-H12","16S-PlA-H10","16S-PlB-H10","16S-PlC-H10","16S-PlD-H10"), ps)

##sample_names(ps_c)
```

```{r}

##Removing ASVs of chloroplast
ps_filt10 <- subset_taxa(ps, Order != "Chloroplast" | is.na(Order))
ps_filt10

##Removing ASVs of mitochondria
ps_filt10 <- subset_taxa(ps_filt10, Family != "Mitochondria" | is.na(Family))
ps_filt10

##Removing ASVs assigned to Eukaryotes and unassigned (NA) at the kingdom level
ps_filt10 <- subset_taxa(ps_filt10, Kingdom != "Eukaryota")
ps_filt10

ps_filt10 <- subset_taxa(ps_filt10, Kingdom != "Unassigned")

ps_filt10
```

```{r}
ntaxa(ps_filt10) # 1,835
# 
get_taxa_unique(ps_filt10, "Phylum") %>% length() #36
get_taxa_unique(ps_filt10, "Class") %>% length() #73
get_taxa_unique(ps_filt10, "Order") %>% length() #179
get_taxa_unique(ps_filt10, "Family") %>% length() #295
get_taxa_unique(ps_filt10, "Genus") %>% length() #484
```
```{r}
##Remove control sample's ASVs

library(decontam)

sample_data(ps_filt10)$is.neg <- sample_data(ps_filt10)$type == "NEG_A"

contamdf.prev <- isContaminant(ps_filt10, method="prevalence", neg="is.neg", threshold=0.5)

table(contamdf.prev$contaminant)
```
```{r}
sample_data(ps_filt10)$is.neg <- sample_data(ps_filt10)$type == "NEG_B"

contamdf.prevB <- isContaminant(ps_filt10, method="prevalence", neg="is.neg", threshold=0.5)

table(contamdf.prevB$contaminant)
```
```{r}
sample_data(ps_filt10)$is.neg <- sample_data(ps_filt10)$type == "NEG_C"

contamdf.prevC <- isContaminant(ps_filt10, method="prevalence", neg="is.neg", threshold=0.5)

table(contamdf.prevC$contaminant)
```
```{r}
sample_data(ps_filt10)$is.neg <- sample_data(ps_filt10)$type == "NEG_D"

contamdf.prevD <- isContaminant(ps_filt10, method="prevalence", neg="is.neg", threshold=0.5)

table(contamdf.prevD$contaminant)
```
```{r}
head(which(contamdf.prevD$contaminant))
```
```{r}
ps.pa <- transform_sample_counts(ps_filt10, function(abund) 1*(abund>0))

ps.pa.neg <- prune_samples(sample_data(ps.pa)$type == "NEG_D", ps.pa)
ps.pa.pos <- prune_samples(sample_data(ps.pa)$type == "S", ps.pa)
# Make data.frame of prevalence in positive and negative samples
df.pa <- data.frame(pa.pos=taxa_sums(ps.pa.pos), pa.neg=taxa_sums(ps.pa.neg),
                      contaminant=contamdf.prevD$contaminant)
ggplot(data=df.pa, aes(x=pa.neg, y=pa.pos, color=contaminant)) + geom_point() +
  xlab("Prevalence (Negative Controls)") + ylab("Prevalence (True Samples)")
```
```{r}
ps_decontam1 <- prune_taxa(!contamdf.prevD$contaminant, ps_filt10)

ps_decontam1
```


```{r}
sample_data(ps_decontam1)$is.neg <- sample_data(ps_decontam1)$type == "C"

contamdf.prev_ext <- isContaminant(ps_decontam1, method="prevalence", neg="is.neg", threshold=0.5)

table(contamdf.prev_ext$contaminant)
```
```{r}
head(which(contamdf.prev_ext$contaminant))
```
```{r}
ps.pa <- transform_sample_counts(ps_decontam1, function(abund) 1*(abund>0))

ps.pa.neg2 <- prune_samples(sample_data(ps.pa)$type == "C", ps.pa)
ps.pa.pos2 <- prune_samples(sample_data(ps.pa)$type == "S", ps.pa)
# Make data.frame of prevalence in positive and negative samples
df.pa2 <- data.frame(pa.pos2=taxa_sums(ps.pa.pos2), pa.neg2=taxa_sums(ps.pa.neg2),
                      contaminant=contamdf.prev_ext$contaminant)
ggplot(data=df.pa2, aes(x=pa.neg2, y=pa.pos2, color=contaminant)) + geom_point() +
  xlab("Prevalence (Negative Controls)") + ylab("Prevalence (True Samples)")
```
```{r}
##Remove controls and contaminants from above

ps_decontam2 <- prune_taxa(!contamdf.prev_ext$contaminant, ps_decontam1)

ps_decontam2
```
```{r}
##Remove overall extraction controls so don't have sample data as "ghost" entries, but at this point associated contamination ASVs already removed above 
ps_cont_final <- subset_samples(ps_decontam2, type != "C")

##Samples overall that were positive ctrl 
ps_cont_final <- subset_samples(ps_cont_final, type != "POS_A")
ps_cont_final <- subset_samples(ps_cont_final, type != "POS_B")
ps_cont_final <- subset_samples(ps_cont_final, type != "POS_C")
ps_cont_final <- subset_samples(ps_cont_final, type != "POS_D")

##Samples overall that were negative ctrl 
ps_cont_final <- subset_samples(ps_cont_final, type != "NEG_A")
ps_cont_final <- subset_samples(ps_cont_final, type != "NEG_B")
ps_cont_final <- subset_samples(ps_cont_final, type != "NEG_C")
ps_cont_final <- subset_samples(ps_cont_final, type != "NEG_D")
```

```{r}
ps

ps_filt10

ps_decontam1

ps_decontam2

ps_cont_final
```

```{r}
library(metagMisc)

ps_filt10_clean <- na.omit(ps_cont_final)

p <- plot_richness(ps_filt10_clean, x="temp", color = "temp",  measures=c("Chao1", "ACE", "Shannon"))

##ps_filtered <- prune_species(speciesSums(ps_filt10) > 0, ps_filt10)

##ps_filtered <- filter_taxa(ps_filt10, function(x) mean(x) > 3, TRUE)
  
```

```{r}
p
```
```{r}
p +  geom_boxplot() + geom_point() + facet_wrap(~reef) 
```

```{r}
ps_Pan <- subset_samples(ps_filt10_clean, gulf=="Panama")
sample_data(ps_Pan)

ps_Chr <- subset_samples(ps_filt10_clean, gulf=="Chiriqui")
sample_data(ps_Chr)

```

```{r}
alpha_Panama <- plot_richness(ps_Pan, x="temp", color = "temp",  measures=c("Chao1", "ACE", "Shannon"))

alpha_Panama  +  geom_boxplot() + geom_point() +  scale_colour_manual(values = c("#0097FF", "#FF8B00", "#F5230E", "#972014")) + theme_bw()
```
```{r}
alpha_Panama  +  geom_boxplot() +  scale_colour_manual(values = c("#0097FF", "#FF8B00", "#F5230E", "#972014")) + theme_bw() 
```
```{r}
###do mtORF 1 and 3 separately

ps_Pan_1 <- subset_samples(ps_Pan, mtorf=="1")
sample_data(ps_Pan_1)

ps_Pan_3 <- subset_samples(ps_Pan, mtorf=="3")
sample_data(ps_Pan_3)

```

```{r}
###mtORF 1 Panama

alpha_Panama_1 <- plot_richness(ps_Pan_1, x="temp", color = "temp",  measures=c("Chao1", "ACE", "Shannon"))

alpha_Panama_1  +  geom_boxplot() + geom_point() +  scale_colour_manual(values = c("#0097FF", "#FF8B00", "#F5230E", "#972014")) + theme_bw()

```

````{r}
###mtORF 3 Panama

alpha_Panama_3 <- plot_richness(ps_Pan_3, x="temp", color = "temp",  measures=c("Chao1", "ACE", "Shannon"))

alpha_Panama_3  +  geom_boxplot() + geom_point() +  scale_colour_manual(values = c("#0097FF", "#FF8B00", "#F5230E", "#972014")) + theme_bw()
```


```{r}
alpha_Chr <- plot_richness(ps_Chr, x="temp", color = "temp",  measures=c("Chao1", "ACE", "Shannon"))

alpha_Chr  +  geom_boxplot() + geom_point() +  scale_colour_manual(values = c("#0097FF", "#FF8B00", "#F5230E", "#972014")) + theme_bw()
```

```{r}
###do mtORF 1 and 3 separately

ps_Chr_1 <- subset_samples(ps_Chr, mtorf=="1")
sample_data(ps_Chr_1)

ps_Chr_3 <- subset_samples(ps_Chr, mtorf=="3")
sample_data(ps_Chr_3)

```

```{r}
##mtORF 1 Chiriqui

alpha_Chr_1 <- plot_richness(ps_Chr_1, x="temp", color = "temp",  measures=c("Chao1", "ACE", "Shannon"))

alpha_Chr_1  +  geom_boxplot() + geom_point() +  scale_colour_manual(values = c("#0097FF", "#FF8B00", "#F5230E", "#972014")) + theme_bw()

```

```{r}
##mtORF 3 Chiriqui

alpha_Chr_3 <- plot_richness(ps_Chr_3, x="temp", color = "temp",  measures=c("Chao1", "ACE", "Shannon"))

alpha_Chr_3  +  geom_boxplot() + geom_point() +  scale_colour_manual(values = c("#0097FF", "#FF8B00", "#F5230E", "#972014")) + theme_bw()

```


```{r}
###Test for stat significance of alpha div trends above

#### first make df with measures of interest and variables

meta = as(sample_data(ps_filt10_clean), "data.frame")

Chao1 <- phyloseq::estimate_richness(ps_filt10_clean, measures = "Chao1")

ACE <- phyloseq::estimate_richness(ps_filt10_clean, measures = "ACE")

Shannon <- phyloseq::estimate_richness(ps_filt10_clean, measures = "Shannon")

adiv <- cbind(Chao1, ACE, Shannon, meta)

head(adiv)
```

```{r}
shapiro.test(adiv$Chao1)
shapiro.test(adiv$ACE)
shapiro.test(adiv$Shannon)


##not normally distributed 
```

```{r}
library(car)
leveneTest(Chao1 ~ gulf * temp * mtorf , data = adiv)
leveneTest(ACE ~ gulf * temp * mtorf, data = adiv)
leveneTest(Shannon ~ gulf * temp * mtorf, data = adiv)

## we do have  Homogeneity of Variance !
```

```{r}
## See if alpha div vary stat significantly 

###Across gulfs 

kruskal.test(Chao1 ~ gulf, data = adiv)

kruskal.test(ACE ~ gulf, data = adiv)

kruskal.test(Shannon ~ gulf, data = adiv)

###Across temp 

kruskal.test(Chao1 ~ temp, data = adiv)

kruskal.test(ACE ~ temp, data = adiv)

kruskal.test(Shannon ~ temp, data = adiv)
```
```{r}
###Pairwise tests

chao1_gulf <- wilcox.test(Chao1 ~ gulf, data = adiv, paired = TRUE)

chao1_gulf
```

```{r}
ACE_gulf <- wilcox.test(ACE ~ gulf, data = adiv, paired = FALSE)

ACE_gulf
```

```{r}

Sh_gulf <- wilcox.test(Shannon ~ gulf, data = adiv, paired = TRUE)

Sh_gulf

```

```{r}

pairwise.wilcox.test(adiv$Chao1, adiv$temp,
                 p.adjust.method = "BH", exact = FALSE)

pairwise.wilcox.test(adiv$ACE, adiv$temp,
                 p.adjust.method = "BH", exact = FALSE)

pairwise.wilcox.test(adiv$Shannon, adiv$temp,
                 p.adjust.method = "BH", exact = FALSE)

#### That’s why we see the warning message “cannot compute exact p-value with ties” above. R uses normal approximation to calculate the p-value. The reason is that the p-value is adjusted by the continuity correction which is supposed to be more accurate. We will not go into detail the concept of continuity correction here. To get the p-value we calculated above, we can use the option correct=FALSE to turn off the continuity correction. 

####Yet with exact = FALSE, same p-value as before ! Sanity check 
```

```{r}
library(FSA)

dunnTest(Chao1 ~ temp,
              data=adiv,
              method="bh")

dunnTest(ACE ~ temp,
              data=adiv,
              method="bh")

dunnTest(Shannon ~ temp,
              data=adiv,
              method="bh")
```

```{r}
##However, need to instead model to best represent interaction effect, as follows: 
```

```{r}
### First run st lm models

mod.chao <- lm(Chao1 ~ temp * gulf * mtorf, data = adiv)

mod.ace <- lm(ACE ~ temp * gulf * mtorf, data = adiv)

mod.shannon <- lm(Shannon ~ temp * gulf * mtorf, data = adiv)
```

```{r}
#Chao
mod.chao.stdres = rstandard(mod.chao)

boxplot(mod.chao.stdres ~ meta$mtorf)

boxplot(mod.chao.stdres ~ meta$gulf)

boxplot(mod.chao.stdres ~ meta$temp)

```

```{r}
#ACE

mod.ace.stdres = rstandard(mod.ace)


##two samples ACE = NaN, let's remove

missing_ace_rows <- which(is.na(adiv$ACE))

missing_ace_rows

rows_to_remove <- c("16S-PlC-A5", "16S-PlB-A10")

rows_to_remove

```
```{r}
missing_ace_rows <- which(is.na(adiv$ACE))

missing_ace_rows

adiv[missing_ace_rows, ]
```


```{r}
meta
```


```{r}

meta_cleaned_ace <- meta[!rownames(meta) %in% rows_to_remove, ]

#SANITY CHECK
print(meta_cleaned_ace)

```


```{R}

boxplot(mod.ace.stdres ~ meta_cleaned_ace$mtorf)

boxplot(mod.ace.stdres ~ meta_cleaned_ace$gulf)

boxplot(mod.ace.stdres ~ meta_cleaned_ace$temp)
```

```{r}
###Shannon

mod.shannon.stdres = rstandard(mod.shannon)

boxplot(mod.shannon.stdres ~ meta$mtorf)

boxplot(mod.shannon.stdres ~ meta$gulf)

boxplot(mod.shannon.stdres ~ meta$temp)

```

```{r}
###Chao1
ggplot(meta, aes(x = gulf, y = mod.chao.stdres)) + geom_boxplot() + 
geom_jitter(height = 0, width = .2)

ggplot(meta, aes(x = mtorf, y = mod.chao.stdres)) + geom_boxplot() + 
geom_jitter(height = 0, width = .2)

ggplot(meta, aes(x = temp, y = mod.chao.stdres)) + geom_boxplot() + 
geom_jitter(height = 0, width = .2)

##ACE
ggplot(meta_cleaned_ace, aes(x = gulf, y = mod.ace.stdres)) + geom_boxplot() + 
  geom_jitter(height = 0, width = .2)

ggplot(meta_cleaned_ace, aes(x = temp, y = mod.ace.stdres)) + geom_boxplot() + 
geom_jitter(height = 0, width = .2)

ggplot(meta, aes(x = gulf, y = mod.shannon.stdres)) + geom_boxplot() + 
geom_jitter(height = 0, width = .2)

ggplot(meta, aes(x = reef, y = mod.shannon.stdres)) + geom_boxplot() + 
geom_jitter(height = 0, width = .2)

ggplot(meta, aes(x = temp, y = mod.shannon.stdres)) + geom_boxplot() + 
geom_jitter(height = 0, width = .2)
```

```{r}
##QQplots

plot(mod.chao.stdres)

plot(mod.ace.stdres)

plot(mod.shannon.stdres)
```

```{r}
##Boxplots st residuals
e.mod.chao <- resid(mod.chao)

boxplot(e.mod.chao~adiv$temp)

##Jitter boxplot with st residuals
ggplot(meta, aes(x = temp, y = e.mod.chao)) + geom_boxplot() + 
geom_jitter(height = 0, width = .2)

##qqplots with st residuals
qqnorm(e.mod.chao,col="firebrick",abline = c(0,1))
```

```{r}
e.mod.ace <- resid(mod.ace)

boxplot(e.mod.ace~meta_cleaned_ace$temp)

#Jitter boxplot with st residuals
ggplot(meta_cleaned_ace, aes(x = temp, y = e.mod.ace)) + geom_boxplot() + 
geom_jitter(height = 0, width = .2)

#qqplots with st residuals
qqnorm(e.mod.ace,col="firebrick",abline = c(0,1))
```

```{r}
e.mod.shannon <- resid(mod.shannon)

boxplot(e.mod.shannon~adiv$temp)

##Jitter boxplot with st residuals
ggplot(meta, aes(x = temp, y = e.mod.shannon)) + geom_boxplot() + 
geom_jitter(height = 0, width = .2)

##qqplots with st residuals
qqnorm(e.mod.shannon,col="firebrick",abline = c(0,1))
```

```{r}

## from above, some issues with errors/variance and thus move onto gls

library(nlme)

chao.gls <- nlme::gls(Chao1 ~ temp * gulf * mtorf, data = adiv, na.action = "na.exclude", weights = varIdent(form = ~ 1|temp), control = list(singular.ok = TRUE))

summary(chao.gls)
##Boxplots st residuals
e.chao.gls <- resid(chao.gls, type = "normalized")

boxplot(e.chao.gls~adiv$temp)

##Jitter boxplot with st residuals
ggplot(adiv, aes(x = temp, y = e.chao.gls)) + geom_boxplot() + 
geom_jitter(height = 0, width = .2)

##qqplots with st residuals
qqnorm(e.chao.gls,col="firebrick",abline = c(0,1))

plot(chao.gls)
```

```{r}
    ace.gls <- nlme::gls(ACE ~ temp * gulf * mtorf, data = adiv, na.action = "na.exclude", weights = varIdent(form = ~ 1|temp), control = list(singular.ok = TRUE))

summary(ace.gls)

###ace.gls <- gls(ACE ~ temp * reef/gulf + geno, data = adiv, na.action = "na.exclude", weights = varIdent(form = ~ 1|temp), control = list(singular.ok = TRUE))


##Boxplots st residuals
e.ace.gls <- resid(ace.gls, type = "normalized")

boxplot(e.ace.gls~adiv$temp)

##Jitter boxplot with st residuals
ggplot(adiv, aes(x = temp, y = e.ace.gls)) + geom_boxplot() + 
geom_jitter(height = 0, width = .2)

##qqplots with st residuals
qqnorm(e.ace.gls,col="firebrick",abline = c(0,1))

plot(ace.gls)
```

```{r}
s.gls <- nlme::gls(Shannon ~ temp * gulf * mtorf, data = adiv, na.action = "na.exclude", weights = varIdent(form = ~ 1|temp), control = list(singular.ok = TRUE))

summary(s.gls)

##Boxplots st residuals
e.s.gls <- resid(s.gls, type = "normalized")

boxplot(e.s.gls~adiv$temp)

##Jitter boxplot with st residuals
ggplot(adiv, aes(x = temp, y = e.s.gls)) + geom_boxplot() + geom_jitter(height = 0, width = .2)

##qqplots with st residuals
qqnorm(e.s.gls,col="firebrick",abline = c(0,1))

plot(s.gls)
```


```{r}

ps_class <- ps_filt10_clean %>%
  tax_glom(taxrank = "Class") %>% 
  transform_sample_counts(function(otu) otu/sum(otu)) %>% 
  psmelt() %>%
  arrange(Class) %>%
  # Adding gulf and temporal variables
  mutate(gulf = sample_data(ps_filt10_clean)$gulf[match(Sample, rownames(sample_data(ps_filt10_clean)))],
         temp = sample_data(ps_filt10_clean)$temp[match(Sample, rownames(sample_data(ps_filt10_clean)))])                                  # Sort data frame alphabetically by class

# Check structure to ensure everything looks correct
str(ps_class) 
```

```{r}
# Filter rows where Class is NA
na_classes <- ps_class %>%
  filter(is.na(Class))

# Print rows with NA in the Class column
print(na_classes)
```

```{r}
# Print all unique values of Class
unique_classes <- unique(ps_class$Class)
print(unique_classes)
```

```{r}
# Count occurrences of each class
class_counts <- table(ps_class$Class)
print(class_counts)
```
```{r}
# Check for NA values in gulf
na_gulf <- ps_class %>% filter(is.na(gulf))
print(na_gulf)

# Check for NA values in temporal
na_temp <- ps_class %>% filter(is.na(temp))
print(na_temp)
```

```{r}
# Check sums of Abundance for each Sample
abundance_sums <- ps_class %>%
  group_by(Sample) %>%
  summarize(Total_Abundance = sum(Abundance), .groups = 'drop')

print(abundance_sums)
```

```{r}
# Check for classes present in each sample
class_summary <- ps_class %>%
  group_by(Sample) %>%
  summarize(Classes = n_distinct(Class), .groups = 'drop')

print(class_summary)
```


```{r}
# Plotting with ggplot
plot_class <- ggplot(ps_class, aes(x = Sample, y = Abundance, fill = Class)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_y_continuous(limits = c(0, 1)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(y = "Relative Abundance", x = "Sample", fill = "Class") +
  theme(
    legend.key.size = unit(0.2, "cm"),  # Adjust legend key size (width and height)
    legend.text = element_text(size = 4),  # Adjust legend text size
    legend.title = element_text(size = 4))  

plot_class
```

```{r}

# Check for missing data in the entire dataset
missing_data_summary <- ps_class %>%
  summarise(
    total_samples = n(),
    missing_samples = sum(is.na(Abundance)),
    missing_temp = sum(is.na(temp)),
    missing_gulf = sum(is.na(gulf))
  )

# Print the summary of missing data
print(missing_data_summary)
```

```{r}
# Identify samples with missing Abundance
missing_abundance_samples <- ps_class %>%
  filter(is.na(Abundance))

# Print samples with missing Abundance
print(missing_abundance_samples)
```

```{r}
# Remove samples with missing Abundance values
ps_class_clean <- ps_class %>%
  filter(!is.na(Abundance))  # Keep only rows where Abundance is not NA

# Check the number of samples in the cleaned dataset
cat("Number of samples after cleaning:", nrow(ps_class_clean), "\n")
```
```{r}
##Do this per gulf/temp combo

filtered_ps_class_28.5_p <- ps_class_clean %>%
  filter(temp == 28.5 & gulf == "Panama")


plot_class_28.5_p <- ggplot(filtered_ps_class_28.5_p, aes(x = Sample, y = Abundance, fill = Class)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_y_continuous(limits = c(0, 1)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(y = "Relative Abundance", x = "Sample", fill = "Class") +
  theme(
    legend.key.size = unit(0.2, "cm"),  # Adjust legend key size (width and height)
    legend.text = element_text(size = 4),  # Adjust legend text size
    legend.title = element_text(size = 4))  


plot_class_28.5_p
```
```{r}
filtered_ps_class_28.5_c <- ps_class_clean %>%
  filter(temp == 28.5 & gulf == "Chiriqui")


plot_class_28.5_c <- ggplot(filtered_ps_class_28.5_c, aes(x = Sample, y = Abundance, fill = Class)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_y_continuous(limits = c(0, 1)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(y = "Relative Abundance", x = "Sample", fill = "Class") +
  theme(
    legend.key.size = unit(0.2, "cm"),  # Adjust legend key size (width and height)
    legend.text = element_text(size = 4),  # Adjust legend text size
    legend.title = element_text(size = 4))  


plot_class_28.5_c
```

```{r}

###30C, Panama
filtered_ps_class_30_p <- ps_class_clean %>%
  filter(temp == 30.0 & gulf == "Panama")


plot_class_30_p <- ggplot(filtered_ps_class_30_p, aes(x = Sample, y = Abundance, fill = Class)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_y_continuous(limits = c(0, 1)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(y = "Relative Abundance", x = "Sample", fill = "Class") +
  theme(
    legend.key.size = unit(0.2, "cm"),  # Adjust legend key size (width and height)
    legend.text = element_text(size = 4),  # Adjust legend text size
    legend.title = element_text(size = 4))  


plot_class_30_p
```
```{r}

###30C, Chiriqui
filtered_ps_class_30_c <- ps_class_clean %>%
  filter(temp == 30.0 & gulf == "Chiriqui")


plot_class_30_c <- ggplot(filtered_ps_class_30_c, aes(x = Sample, y = Abundance, fill = Class)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_y_continuous(limits = c(0, 1)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(y = "Relative Abundance", x = "Sample", fill = "Class") +
  theme(
    legend.key.size = unit(0.2, "cm"),  # Adjust legend key size (width and height)
    legend.text = element_text(size = 4),  # Adjust legend text size
    legend.title = element_text(size = 4))  


plot_class_30_c
```
```{r}
###33C, Panama
filtered_ps_class_33_p <- ps_class_clean %>%
  filter(temp == 33.0 & gulf == "Panama")


plot_class_33_p <- ggplot(filtered_ps_class_33_p, aes(x = Sample, y = Abundance, fill = Class)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_y_continuous(limits = c(0, 1)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(y = "Relative Abundance", x = "Sample", fill = "Class") +
  theme(
    legend.key.size = unit(0.2, "cm"),  # Adjust legend key size (width and height)
    legend.text = element_text(size = 4),  # Adjust legend text size
    legend.title = element_text(size = 4))  


plot_class_33_p
```
```{r}
###33C, Chiriqui
filtered_ps_class_33_c <- ps_class_clean %>%
  filter(temp == 33.0 & gulf == "Chiriqui")


plot_class_33_c <- ggplot(filtered_ps_class_33_c, aes(x = Sample, y = Abundance, fill = Class)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_y_continuous(limits = c(0, 1)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(y = "Relative Abundance", x = "Sample", fill = "Class") +
  theme(
    legend.key.size = unit(0.2, "cm"),  
    legend.text = element_text(size = 4), 
    legend.title = element_text(size = 4))  


plot_class_33_c
```
```{r}
###36C, Panama
filtered_ps_class_36_p <- ps_class_clean %>%
  filter(temp == 36.0 & gulf == "Panama")


plot_class_36_p <- ggplot(filtered_ps_class_36_p, aes(x = Sample, y = Abundance, fill = Class)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_y_continuous(limits = c(0, 1)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(y = "Relative Abundance", x = "Sample", fill = "Class") +
  theme(
    legend.key.size = unit(0.5, "cm"),  # Adjust legend key size (width and height)
    legend.text = element_text(size = 8),  # Adjust legend text size
    legend.title = element_text(size = 8))  


plot_class_36_p
```
```{r}
###36C, Chiriqui
filtered_ps_class_36_c <- ps_class_clean %>%
  filter(temp == 36.0 & gulf == "Chiriqui")


plot_class_36_c <- ggplot(filtered_ps_class_36_c, aes(x = Sample, y = Abundance, fill = Class)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_y_continuous(limits = c(0, 1)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(y = "Relative Abundance", x = "Sample", fill = "Class") +
  theme(
    legend.key.size = unit(0.5, "cm"),  # Adjust legend key size (width and height)
    legend.text = element_text(size = 5),  # Adjust legend text size
    legend.title = element_text(size = 8))  


plot_class_36_c
```


```{r}
##Genera changes only at 36C? 

ps_gen <- ps_filt10_clean %>%
  tax_glom(taxrank = "Genus") %>% 
  transform_sample_counts(function(otu) otu/sum(otu)) %>% 
  psmelt() %>%
  filter(Abundance > 0.02) %>%
  arrange(Genus) %>%
  # Adding gulf and temporal variables
  mutate(gulf = sample_data(ps_filt10_clean)$gulf[match(Sample, rownames(sample_data(ps_filt10_clean)))],
         temp = sample_data(ps_filt10_clean)$temp[match(Sample, rownames(sample_data(ps_filt10_clean)))])%>%                                  
  group_by(Sample) %>%
  mutate(Abundance = Abundance / sum(Abundance)) %>%  # Normalize to sum to 1
  ungroup()  

# Sanity check
str(ps_gen) 
```

```{r}

# Check the sums of Abundance for each sample to ensure they equal 1
check_sums <- ps_gen %>%
  group_by(Sample) %>%
  summarise(total_abundance = sum(Abundance), .groups = 'drop')

print(check_sums)
```

```{r}
# Remove samples with missing Abundance values
ps_gen_clean <- ps_gen %>%
  filter(!is.na(Abundance))  # Keep only rows where Abundance is not NA

# Check the number of samples in the cleaned dataset
cat("Number of samples after cleaning:", nrow(ps_gen_clean), "\n")
```

```{r}
###36C, Chiriqui
filtered_ps_gen_36_c <- ps_gen_clean %>%
  filter(temp == 36.0 & gulf == "Chiriqui")


plot_gen_36_c <- ggplot(filtered_ps_gen_36_c, aes(x = Sample, y = Abundance, fill = Genus)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_y_continuous(limits = c(0, 1)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(y = "Relative Abundance", x = "Sample", fill = "Genus") +
  theme(
    legend.key.size = unit(0.4, "cm"),  # Adjust legend key size (width and height)
    legend.text = element_text(size = 5),  # Adjust legend text size
    legend.title = element_text(size = 8))  


plot_gen_36_c
```
```{r}
###28.5C, Chiriqui
filtered_ps_gen_28.5_c <- ps_gen_clean %>%
  filter(temp == 28.5 & gulf == "Chiriqui")


plot_gen_28.5_c <- ggplot(filtered_ps_gen_28.5_c, aes(x = Sample, y = Abundance, fill = Genus)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_y_continuous(limits = c(0, 1)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(y = "Relative Abundance", x = "Sample", fill = "Genus") +
  theme(
    legend.key.size = unit(0.5, "cm"),  # Adjust legend key size (width and height)
    legend.text = element_text(size = 6),  # Adjust legend text size
    legend.title = element_text(size = 8))  


plot_gen_28.5_c
```
```{r}
###28.5C, Panama
filtered_ps_gen_28.5_p <- ps_gen_clean %>%
  filter(temp == 28.5 & gulf == "Panama")


plot_gen_28.5_p <- ggplot(filtered_ps_gen_28.5_p, aes(x = Sample, y = Abundance, fill = Genus)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_y_continuous(limits = c(0, 1)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(y = "Relative Abundance", x = "Sample", fill = "Genus") +
  theme(
    legend.key.size = unit(0.5, "cm"),  # Adjust legend key size (width and height)
    legend.text = element_text(size = 6),  # Adjust legend text size
    legend.title = element_text(size = 8))  


plot_gen_28.5_p
```
```{r}
###36C, Panama
filtered_ps_gen_36_p <- ps_gen_clean %>%
  filter(temp == 36.0 & gulf == "Panama")


plot_gen_36_p <- ggplot(filtered_ps_gen_36_p, aes(x = Sample, y = Abundance, fill = Genus)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_y_continuous(limits = c(0, 1)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(y = "Relative Abundance", x = "Sample", fill = "Genus") +
  theme(
    legend.key.size = unit(0.5, "cm"),  # Adjust legend key size (width and height)
    legend.text = element_text(size = 6),  # Adjust legend text size
    legend.title = element_text(size = 8))  


plot_gen_36_p
```

```{r}
## Remove singletons
ps_filtered  <- filter_taxa(ps_filt10_clean, function(x) sum(x > 1) > 1, TRUE)

```

```{r}
##compare original vs filtered ps file

ps 

ps_filt10_clean

ps_filtered
```


```{r}
###rlog transformation
library(GenomicRanges)
library("SummarizedExperiment")

otu_table(ps_filtered) <- otu_table(ps_filtered) + 1 

##add 1 pseudocount

dds = phyloseq_to_deseq2(ps_filtered, ~ 1)
rld <- DESeq2::rlog(dds, blind = TRUE, fitType = "local")

##note: fitType='parametric', but the dispersion trend was not well captured by thefunction: y = a/x + b, and a local regression fit was automatically substituted. specify fitType='local' or 'mean' to avoid this message next time.

```

```{r}
library(DESeq2)
rlogMat <- assay(rld)
physeq1 = ps_filtered
otu_table(physeq1) <- otu_table(rlogMat, taxa_are_rows = TRUE)

```

```{r}
physeq1

table(tax_table(physeq1)[, "Kingdom"], exclude = NULL)

table(tax_table(physeq1)[, "Phylum"], exclude = NULL)

table(tax_table(physeq1)[, "Class"], exclude = NULL)

table(tax_table(physeq1)[, "Order"], exclude = NULL)

table(tax_table(physeq1)[, "Genus"], exclude = NULL)

table(tax_table(physeq1)[, "Species"], exclude = NULL)
```

```{r}

## Set random seed for reproducibility 

set.seed(8765)

```
```{r}
###Let's run the pairwise dissimilarity index, Horn-Morisita index
####From reading papers online, you first make an incidence matrix via vegdist, and then run this matrix viaa Mantel test

  
sample_df <- sample_data(physeq1)

sample_df ###sanity check
  
temp_vector <- sample_df$temp

temp_vector ###sanity check
  
```

````{r}
###Calculate Horn index 

horn_physeq <- phyloseq::distance(physeq1, "horn")

### horn_physeq ; sanity check, all looks good!

```

````{r}
  
#environmental vectors - euclidean distance
dist.temp = dist(temp_vector, method = "euclidean")  
  
```

```{r}

###Let's see if this makes sense of first principle = using the dataset for all pts together

horn_temp  = mantel(horn_physeq, dist.temp, method = "spearman", permutations = 9999, na.rm = TRUE)
```
```{r}
###Summary results

horn_temp
```
```{r}
###Now let's do this with mtORF 1 and 3 within each gulf

###Panama

physeq1_Pan <- subset_samples(physeq1, gulf=="Panama")
sample_data(physeq1_Pan)

physeq1_Pan_1 <- subset_samples(physeq1_Pan, mtorf=="1")
sample_data(physeq1_Pan_1)

physeq1_Pan_3 <- subset_samples(physeq1_Pan, mtorf=="3")
sample_data(physeq1_Pan_3)
```

```{r}
###Chiriqui

physeq1_Chr <- subset_samples(physeq1, gulf=="Chiriqui")
sample_data(physeq1_Chr)

physeq1_Chr_1 <- subset_samples(physeq1_Chr, mtorf=="1")
sample_data(physeq1_Chr_1)

physeq1_Chr_3 <- subset_samples(physeq1_Chr, mtorf=="3")
sample_data(physeq1_Chr_3)

```

```{r}
###mtORF 1, Panama

sample_df_Pan_1 <- sample_data(physeq1_Pan_1)

sample_df_Pan_1 ###sanity check
  
temp_vector_Pan_1 <- sample_df_Pan_1$temp

temp_vector_Pan_1 ###sanity check
```

```{r}

###Calculate Horn index 

horn_physeq_Pan_1 <- phyloseq::distance(physeq1_Pan_1, "horn")
  
#environmental vectors - euclidean distance
dist.temp_Pan_1 = dist(temp_vector_Pan_1, method = "euclidean")  

horn_temp_Pan_1  = mantel(horn_physeq_Pan_1, dist.temp_Pan_1, method = "spearman", permutations = 9999, na.rm = TRUE)

horn_temp_Pan_1
```
```{r}
###mtORF 3, Panama

sample_df_Pan_3 <- sample_data(physeq1_Pan_3)

sample_df_Pan_3 ###sanity check
  
temp_vector_Pan_3 <- sample_df_Pan_3$temp

temp_vector_Pan_3 ###sanity check
```

```{r}

###Calculate Horn index 

horn_physeq_Pan_3 <- phyloseq::distance(physeq1_Pan_3, "horn")
  
#environmental vectors - euclidean distance
dist.temp_Pan_3 = dist(temp_vector_Pan_3, method = "euclidean")  

horn_temp_Pan_3  = mantel(horn_physeq_Pan_3, dist.temp_Pan_3, method = "spearman", permutations = 9999, na.rm = TRUE)

horn_temp_Pan_3
```
```{r}
###mtORF 1, Chiriqui

sample_df_Chr_1 <- sample_data(physeq1_Chr_1)

sample_df_Chr_1  ###sanity check
  
temp_vector_Chr_1 <- sample_df_Chr_1$temp

temp_vector_Chr_1 ###sanity check
```

```{r}

###Calculate Horn index 

horn_physeq_Chr_1 <- phyloseq::distance(physeq1_Chr_1, "horn")
  
#environmental vectors - euclidean distance
dist.temp_Chr_1 = dist(temp_vector_Chr_1, method = "euclidean")  

horn_temp_Chr_1  = mantel(horn_physeq_Chr_1, dist.temp_Chr_1, method = "spearman", permutations = 9999, na.rm = TRUE)

horn_temp_Chr_1
```
```{r}
###mtORF 3, Chiriqui

sample_df_Chr_3 <- sample_data(physeq1_Chr_3)

sample_df_Chr_3  ###sanity check
  
temp_vector_Chr_3 <- sample_df_Chr_3$temp

temp_vector_Chr_3 ###sanity check
```

```{r}

###Calculate Horn index 

horn_physeq_Chr_3 <- phyloseq::distance(physeq1_Chr_3, "horn")
  
#environmental vectors - euclidean distance
dist.temp_Chr_3 = dist(temp_vector_Chr_3, method = "euclidean")  

horn_temp_Chr_3  = mantel(horn_physeq_Chr_3, dist.temp_Chr_3, method = "spearman", permutations = 9999, na.rm = TRUE)

horn_temp_Chr_3
```

```{r}

```


```{r}
# agglomerate taxa

##top 10 order only

phylum.sum = tapply(taxa_sums(physeq1), tax_table(physeq1)[, "Order"], sum, na.rm=TRUE)
top10 = names(sort(phylum.sum, TRUE))[1:10]
physeq2 = prune_taxa((tax_table(physeq1)[, "Order"] %in% top10), physeq1)
```

```{r}
physeq2
```

```{r}

ps.rel = transform_sample_counts(physeq2, function(otu) otu/sum(otu)*100)

glom <- tax_glom(ps.rel , taxrank = "Order", NArm = FALSE)

## remove NAs

glom2 <- phyloseq_rm_na_tax(glom) 

ps.melt <- psmelt(glom2)

# change to character for easy-adjusted level
ps.melt$Order <- as.character(ps.melt$Order)

ps.melt <- ps.melt %>%
  group_by(reef, Order) %>%
  mutate(median=median(Abundance))

ps.melt <- na.omit(ps.melt)
```


```{r}

##Genera across temp

Order_temp <- ggplot(ps.melt, aes(x = temp, y = Order, color = Order)) + geom_point(aes(size = Abundance)) + scale_colour_hue(guide = "none") +  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"))

Order_temp
```

```{r fig.width=15, fig.height=4}

# Fix reef levels in sample_data

sample_data(physeq1)$reef <- factor(
  sample_data(physeq1)$reef, 
  levels = c("AFU_A", "UVA_A", "MOG_A", "SAB_A"))


p2 <- Order_temp + facet_wrap(~gulf, 1) + theme(panel.spacing = unit(1, "lines")) + scale_x_discrete(expand = c(0, 1))

p2
```

```{r}

ps_phylum <- physeq2 %>%
  tax_glom(taxrank = "Order") %>%                     # agglomerate at class level
  transform_sample_counts(function(otu) otu/sum(otu)*100) %>% # Transform to rel. abundance
  psmelt() %>%                                         # Melt to long format
  filter(Abundance > 0.02) %>%                         # Filter out low abundance taxa
  arrange("Order")                                      # Sort data frame alphabetically by phylum

```

```{r}

# Plot 
ggplot(ps_phylum, aes(x = temp, y = Abundance, fill = Order)) + 
  facet_grid(gulf~.) +
  geom_bar(stat = "identity") + theme_bw()
```

```{r}
set.seed(111)
library(viridis)

Temp_differences_gulf_mtORF <-
  ggplot(ps_phylum, aes(x = temp, y=Abundance, fill = Order)) +
  geom_col(position = "fill") +
  facet_wrap(gulf~mtorf, scales = "free", ncol = 5) +
  labs(title = "Prokaryotic relative abundances across mtORF type and Gulf", x= "mtORF Type", y = "Relative abundance", fill = "Order") +
  theme_bw() 

Temp_differences_gulf_mtORF + scale_fill_viridis(discrete = TRUE)
```

```{r}

dotplot_temp_differences_gulf_mtORF  <- ggplot(ps_phylum, aes(x = temp, y = Order, color = Order)) + geom_point(aes(size = Abundance)) +  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) 

dotplot_temp_differences_gulf_mtORF

dotplot_temp_differences_gulf_mtORF + facet_wrap(gulf~mtorf)
  
```

```{r}
library(scales)

set.seed(10003)

ord <- ordinate(physeq1, "PCoA", "bray")

# Fix reef levels in sample_data
sample_data(physeq1)$reef <- factor(
  sample_data(physeq1)$reef, 
  levels = c("AFU_A", "UVA_A", "MOG_A", "SAB_A"))

```

```{r}
p1 = plot_ordination(physeq1, ord, color="temp") + stat_ellipse()
p1 
```

```{r}
p2 <- p1 + facet_wrap(~reef, 1) + stat_ellipse() +  scale_colour_manual(values = c("#0097FF", "#FF8B00", "#F5230E", "#972014"))  + theme_bw()  

p2
```
```{r}
p3 <- p1 + facet_wrap(~gulf, 1) + stat_ellipse() +  scale_colour_manual(values = c("#0097FF", "#FF8B00", "#F5230E", "#972014"))  + theme_bw()  

p3 
```

```{r}
set.seed(10003)

ps_nmds <- ordinate(
  physeq = physeq1, 
  method = "NMDS", 
  distance = "bray"
)
```

```{r}
plot_ordination(
  physeq = physeq1,
  ordination = ps_nmds,
  color = "temp",
  shape = "reef") 

```

```{r}
plot_ordination(
  physeq = physeq1,
  ordination = ps_nmds,
  color = "temp") + facet_wrap(~reef, 1) + stat_ellipse() +  scale_colour_manual(values = c("#0097FF", "#FF8B00", "#F5230E", "#972014"))  + theme_bw()  

```

```{r}
plot_ordination(
  physeq = physeq1,
  ordination = ps_nmds,
  color = "temp") + facet_wrap(~gulf, 1) + stat_ellipse() +  scale_colour_manual(values = c("#0097FF", "#FF8B00", "#F5230E", "#972014"))  + theme_bw()  
```
```{r}
plot_ordination(
  physeq = physeq1,
  ordination = ps_nmds,
  color = "temp") + facet_wrap(~geno, 1) + stat_ellipse() +  scale_colour_manual(values = c("#0097FF", "#FF8B00", "#F5230E", "#972014"))  + theme_bw() 
```
```{r}
plot_ordination(
  physeq = physeq1,
  ordination = ps_nmds, 
  color = "geno", shape = "temp") + facet_wrap(~gulf, 1) 
```

```{r}
###Let's do something more straight forward with the same input as for our ordination plots -- why not show differences in beta diversity using Bray-Curtis? 

set.seed(555)
```

```{r}
###Let's create a matrix of just bray-curtis dissimilarity indices for our ps obj

###If we were to see the same trends/gain same insights from our CAP plot, the variance across temperatures 

bc_dist_entiredat <- phyloseq::distance(physeq1, method = "bray")

head(bc_dist_entiredat)
```

```{r}
###turn into matrix 

bc_dist_entiredat_matrix <- as.matrix(bc_dist_entiredat)

bc_dist_entiredat_matrix

```

```{r}
###turn to df

bc_dist_entiredat_df <- as.data.frame(as.table(bc_dist_entiredat_matrix)) 

bc_dist_entiredat_df
```

```{r}
colnames(bc_dist_entiredat_df) <- c("Sample1", "Sample2", "Distance")

###looks good!

bc_dist_entiredat_df
```

```{r}
###Remove samples compared to themselves, re sa1 vs sa1

bc_dist_entiredat_df <- bc_dist_entiredat_df[bc_dist_entiredat_df$Sample1 != bc_dist_entiredat_df$Sample2, ]

bc_dist_entiredat_df

class(bc_dist_entiredat_df)

```

```{r}
##Let's map and add metadata

metadata_matrix <- as.matrix(sample_data(physeq1)) ##first turn to matrix

metadata_bc <- as.data.frame(metadata_matrix)

metadata_bc

class(metadata_bc)
```

```{r}
###The row names here are what is being denoted as the sample ID in the bray-curtis df, re Sample1 and Sample2 values. Let's name this a new column:

metadata_bc <- metadata_bc %>%
  rownames_to_column(var = "SampleID")

metadata_bc
```

```{r}

##Let's merge it all together, metadata + df with bc calc

temp_meta <- metadata_bc %>% dplyr::select(SampleID, temp)

temp_meta
```

```{r}

bc_dist_entiredat_df_meta <- bc_dist_entiredat_df %>%
  left_join(temp_meta, by = c("Sample1" = "SampleID")) %>%
  mutate(temp1 = temp) %>%  # Use mutate to assign temp1 explicitly
  select(-temp) %>%  # Remove the intermediate temp column
  left_join(temp_meta, by = c("Sample2" = "SampleID")) %>%
  mutate(temp2 = temp) %>%  # Assign temp2 explicitly
  select(-temp)  # Remove the intermediate temp column

```

```{r}
###Let's see how it looks

bc_dist_entiredat_df_meta

#wohoo! 

```

```{r}
###Okay let's try to plot this!!!

###If our goal is to show an INCREASE in community variance at 36C, this needs to be done by plotting within temp values

# Filter for within-temperature comparisons
same_temp_bc <- bc_dist_entiredat_df_meta %>%
  filter(temp1 == temp2) %>% # Keep rows where temp1 equals temp2
  mutate(Temperature = temp1) # Assign a single temperature column

same_temp_bc
```

```{r}

# Plot
ggplot(same_temp_bc, aes(x = factor(Temperature), y = Distance)) +
  geom_boxplot() +
  labs(x = "Temperature", y = "Bray-Curtis Distance", title = "Community dissimilarity within a temperature") +
  theme_bw()
```

```{r}
###Who are these outliers?

outliers_bc <- same_temp_bc %>%
  group_by(Temperature) %>%
  summarise(
    Q1 = quantile(Distance, 0.25),
    Q3 = quantile(Distance, 0.75),
    IQR = Q3 - Q1
  ) %>%
  mutate(
    Lower = Q1 - 1.5 * IQR,
    Upper = Q3 + 1.5 * IQR
  ) %>%
  select(Temperature, Lower, Upper)

# Join back and filter the outliers
outlier_bc_rows <- same_temp_bc %>%
  left_join(outliers_bc, by = "Temperature") %>%
  filter(Distance < Lower | Distance > Upper)

print(outlier_bc_rows)
```
```{r}
###Are some samples disproportionately represented here?

library(dplyr)

# occurence of Sample1 and Sample2
count_sample1 <- outlier_bc_rows %>%
  dplyr::count(Sample1, name = "count_sample1")

count_sample2 <- outlier_bc_rows %>%
  dplyr::count(Sample2, name = "count_sample2")
```

```{r}
###Let's see
count_sample1
###16S-PlA-A10, 16S-PlA-A7, 16S-PlA-C3, 16S-PlD-A10, 

count_sample2
###16S-PlA-A10, 16S-PlA-A7, 16S-PlA-C3, 16S-PlD-A10, 

###Okay sanity checked out -- who are these samples? 

```
```{r}
metadata_bc

###16S-PlA-A10: 722	MOG_A	Panama	3	33
###16S-PlA-A7: 716	SAB_A	Panama	3	30	S	9
###16S-PlA-C3: 727	MOG_A	Panama	3	28.5	S	9
###16S-PlD-A10: 732	MOG_A	Panama	3	30	S	9

```
