
```{r}

##Now truly only coral samples, and sample names ~ gulf/reef sites!
setwd("~/holobiont_2020-2021/PCA_19Sep2022")

set.seed(12222)

###load pckgs

library(vctrs)
library(readr)
library(tidyverse)

```

```{r}
##RDA to link upwelling regime's signal local adaptation to physiological outcome in CBASS

library("smartsnp")
library("poppr")    
library("magrittr")
library('vcfR')
library("ggplot2")
library("RColorBrewer")
library("readr")
library("devtools")


vcf_file <- file.path("~/holobiont_2020-2021/PCA_19Sep2022/poppr/coral_onlyFILTER_bcftools_19Sep2022.vcf.gz")

original_vcf <- read.vcfR("~/holobiont_2020-2021/PCA_19Sep2022/poppr/coral_onlyFILTER_bcftools_19Sep2022.vcf.gz")

head(original_vcf)

### with mtORF

pop.data <- read.table("C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\population.gbs_final_mtorf_FINAL_18Oct2023.csv", sep = ",", header = TRUE)

pop.data

```
```{r}
sample_names_vcf <- colnames(extract.gt(original_vcf))
head(sample_names_vcf)

###Yes sanity check, sample metadata order matches vcf

vcf_rename <- read.vcfR("C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\coral_onlyFILTER_rename_19Sep2022.vcf")
```

```{r}
sample_names_vcf <- colnames(extract.gt(vcf_rename))
head(vcf_rename)
```

```{r}

oldwd <- getwd()

setwd("C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022")

file.copy(from = vcf_file, to = "./") # Copy the file to the cwd

```

```{r}
system("plink --vcf coral_onlyFILTER_rename_19Sep2022.vcf --double-id --allow-extra-chr --set-missing-var-ids @:# --indep-pairwise 50 10 0.1 --make-bed --out LD_pruned_bed_region")

### 110193 of 116338 variants removed = 6145 var kept
```

```{r}
###New, pruned file

system("plink --vcf coral_onlyFILTER_rename_19Sep2022.vcf --double-id --allow-extra-chr --set-missing-var-ids @:# --extract LD_pruned_bed_region.prune.in --make-bed --out coral_pruneddata") 

```

```{r}

###Pruned output to vcf


system("plink --bfile coral_pruneddata --double-id --allow-extra-chr --set-missing-var-ids @:# --recode vcf --out vcf_pruned_final_13Feb2024")

```

```{r}

### Pruned to traw

### --recode A-transpose --double-id --allow-extra-chr --out region_genotypeMatrix 

system("plink --bfile coral_pruneddata --recode A-transpose --double-id --allow-extra-chr --set-missing-var-ids @:# --out matrix_vcf_pruned_final_13Feb2024")

```

```{r}
# Load the PLINK (.fam) file to get the number of samples
numSamples = nrow(read.table("coral_pruneddata.fam"))

numSamples
```
```{r}
##Set group variables

pop.data

```

```{r}

numSamples

my_groups <- c(data.table::fread("C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\population.gbs_final_mtorf_FINAL_18Oct2023.csv", header = TRUE))[[4]]

my_groups


my_groups_orf <- c(data.table::fread("C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\population.gbs_final_mtorf_FINAL_18Oct2023.csv", header = TRUE))[[5]]

my_groups_orf
```

```{r}
length(table(my_groups)) #number of reefs

table(my_groups)

length(table(my_groups_orf)) #number of mtORFs

table(my_groups_orf)
```

```{r}

# Running smart_pca
reef.sm.pca <- smart_pca(snp_data = "matrix_vcf_pruned_final_13Feb2024.traw", 
                    sample_group = my_groups,
                    missing_value = NA, 
                    scaling = "drift",
                    pc_axes = 6)
```
```{r}
reef.sm.pca
```

```{r}
# Here is a plot of the first two components:
plot(reef.sm.pca$pca.sample_coordinates[,c("PC1","PC2")])
```


```{r}
##inspect sm.pca object

class(reef.sm.pca)

names(reef.sm.pca)

str(reef.sm.pca)

```

```{r}
pcaR_eigen <- reef.sm.pca$pca.eigenvalues # extract eigenvalues (PCA1 and PC2 axes explain 3.5% variation in SNP variation across individuals)

pcaR_eigen

pcaR_load <- reef.sm.pca$pca.snp_loadings # extract principal coefficients (high SNP loadings indicate loci with stronger variation across individuals)

pcaR_load 

pcaR_coord <- reef.sm.pca$pca.sample_coordinates # extract principal components (position of individuals in PCA space used to generate the ordination)

pcaR_coord
```

```{r}
cols <- c("#DE1BEB", "#EB1BA3", "#1ED2EB", "#B9F4FF", "#20A4E6", "#EF94EC")
                
```

```{r}
plot(reef.sm.pca$pca.sample_coordinates[,c("PC1","PC2")], cex = 1.5, 
     bg = cols[as.factor(my_groups)], pch = 21, col = "black", main = "Panama TEP WGBS smartpca, by reef")
legend("topright", legend = levels(as.factor(my_groups)), cex = 1, pch = 21, 
       pt.cex = 1.0, col = "black", pt.bg = cols, text.col = cols)

plot(reef.sm.pca$pca.sample_coordinates[,c("PC1","PC3")], cex = 1.5, 
     bg = cols[as.factor(my_groups)], pch = 21, col = "black", main = "Panama TEP WGBS smartpca, by reef")
legend("topright", legend = levels(as.factor(my_groups)), cex = 1, pch = 21, 
       pt.cex = 1.0, col = "black", pt.bg = cols, text.col = cols)

plot(reef.sm.pca$pca.sample_coordinates[,c("PC1","PC4")], cex = 1.5, 
     bg = cols[as.factor(my_groups)], pch = 21, col = "black", main = "Panama TEP WGBS smartpca, by reef")
legend("topright", legend = levels(as.factor(my_groups)), cex = 1, pch = 21, 
       pt.cex = 1.0, col = "black", pt.bg = cols, text.col = cols)
```

```{r}
gulf <- c(data.table::fread("C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\population.gbs_final.csv", header = TRUE))[[2]]

gulf
```
```{r}

length(table(gulf)) #number of gulfs

table(gulf)
```

```{r}

# Running smart_pca
gulf.sm.pca <- smart_pca(snp_data = "region_genotypeMatrix.traw", 
                    sample_group = gulf,
                    missing_value = NA,
                    scaling = "drift")

# Here is a plot of the first two components:
plot(gulf.sm.pca$pca.sample_coordinates[, c(3,4)])
```

```{r}

##inspect gulf.sm.pca object

class(gulf.sm.pca)

names(gulf.sm.pca)

str(gulf.sm.pca)

```

```{r}
pcaG_eigen <- gulf.sm.pca$pca.eigenvalues 

pcaG_eigen

# extract eigenvalues (PCA1 and PC2 axes explain 3.5% variation in SNP variation across individuals)


pcaG_load <- gulf.sm.pca$pca.snp_loadings 

pcaG_load 

# extract principal coefficients (high SNP loadings indicate loci with stronger variation across individuals)


pcaG_coord <- gulf.sm.pca$pca.sample_coordinates 

pcaG_coord 

# extract principal components (position of individuals in PCA space used to generate the ordination)
```

```{r}
##cols <- rainbow(length(table(gulf)))


cols <- c("#FF33FF", 
                "#56B4E9")
                
plot(gulf.sm.pca$pca.sample_coordinates[,c("PC1","PC2")], cex = 1.5, 
     bg = cols[as.factor(gulf)], pch = 21, col = "black", main = "Panama TEP WGBS smartpca, by gulf")
legend("topright", legend = levels(as.factor(gulf)), cex = 1, pch = 21, 
       pt.cex = 1.0, col = "black", pt.bg = cols, text.col = cols)
```



```{r}
### Now ... does mtORF explain some of these trends above, particularly the seemingly fixed value of PC2?

# Running smart_pca
orf.sm.pca <- smart_pca(snp_data = "region_genotypeMatrix.traw", 
                    sample_group = my_groups_orf,
                    missing_value = NA,
                    scaling = "drift")

# Here is a plot of the first two components:
plot(orf.sm.pca$pca.sample_coordinates[, c(3,4)])

##inspect gulf.sm.pca object

class(orf.sm.pca)

names(orf.sm.pca)

str(orf.sm.pca)
```

```{r}
pcaO_eigen <- orf.sm.pca$pca.eigenvalues 

pcaO_eigen

# extract eigenvalues (PCA1 and PC2 axes explain 3.5% variation in SNP variation across individuals)

pcaO_load <- orf.sm.pca$pca.snp_loadings 

pcaO_load 

# extract principal coefficients (high SNP loadings indicate loci with stronger variation across individuals)

```

```{r}
pcaO_coord <-orf.sm.pca$pca.sample_coordinates 

pcaO_coord 

# extract principal components (position of individuals in PCA space used to generate the ordination)

##cols <- rainbow(length(table(gulf)))

```

```{r}

###Plot smartPCA per MLG

cols <- c("#FFC300", "#581845")
                
plot(orf.sm.pca$pca.sample_coordinates[,c("PC1","PC2")], cex = 1.5, 
     bg = cols[as.factor(my_groups_orf)], pch = 21, col = "black", main = "Panama TEP WGBS smartpca, by mtorf")
legend("topright", legend = levels(as.factor(my_groups_orf)), cex = 1, pch = 21, 
       pt.cex = 1.0, col = "black", pt.bg = cols, text.col = cols)
```
```{r}
###Let's see who or what is driving differences across the two PCs via histograms

##PC2, reefsite

###First, extract only sample coord into own obj

PCA_reef <- reef.sm.pca$pca.sample_coordinates

PCA_reef

```

```{r}

p1_reef <- ggplot(PCA_reef, aes(x=PC1, color = Group, fill = Group)) + geom_histogram()
p1_reef +  geom_rug()

p2_reef <- ggplot(PCA_reef, aes(x=PC2, color = Group, fill = Group)) + geom_histogram()
p2_reef +  geom_rug()
```

```{r}
## Repeat with gulf

PCA_gulf <- gulf.sm.pca$pca.sample_coordinates

PCA_gulf
```

```{r}

p1_gulf <- ggplot(PCA_gulf, aes(x=PC1, color = Group, fill = Group)) + geom_histogram()
p1_gulf +  geom_rug()

p2_gulf <- ggplot(PCA_gulf, aes(x=PC2, color = Group, fill = Group)) + geom_histogram()
p2_gulf +  geom_rug()
```
```{r}
PCA_orf <- orf.sm.pca$pca.sample_coordinates

PCA_orf

PCA_orf$Group <- as.factor(PCA_orf$Group)

PCA_orf
```

```{r}

p1_orf <- ggplot(PCA_orf, aes(x=PC1, color = Group, fill = Group)) + geom_histogram()
p1_orf +  geom_rug()

p2_orf <- ggplot(PCA_orf, aes(x=PC2, color = Group, fill = Group)) + geom_histogram()
p2_orf +  geom_rug()
```


```{r}
gulf <- c(data.table::fread("C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\population.gbs_final.csv", header = TRUE))[[2]]

permanova_gulf <- smart_permanova(snp_data = "region_genotypeMatrix.traw", sample_group = gulf, 
                              target_space = "pca",  missing_value = NA, scaling = "drift", pairwise = "TRUE", permutation_seed = 1234)

perm_gulf <- permanova_gulf$permanova.samples

permanova_gulf$permanova.global_test

head(permanova_gulf$permanova.pairwise_test)
```

```{r}

my_groups <- c(data.table::fread("C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\population.gbs_final.csv", header = TRUE))[[4]]

my_groups

permanova_reef <- smart_permanova(snp_data = "region_genotypeMatrix.traw", sample_group = my_groups, missing_value = NA, scaling = "drift", target_space = "pca", pairwise = "TRUE", permutation_seed = 1234)
```

```{r}
perm_reef <- permanova_reef$permanova.samples

permanova_reef$permanova.global_test

head(permanova_reef$permanova.pairwise_test)
```
```{r}

my_groups_orf <- c(data.table::fread("C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\population.gbs_final_mtorf_FINAL_18Oct2023.csv", header = TRUE))[[5]]

my_groups_orf
```

```{r}
my_groups_orf <- na.omit(my_groups_orf)

my_groups_orf

```

```{r}
set.seed(1555)
###Let's re-do the pruned loci but with unique sample names

system("plink --vcf coral_onlyFILTER_bcftools_19Sep2022.vcf --double-id --allow-extra-chr --set-missing-var-ids @:# --indep-pairwise 50 10 0.1 --make-bed --out uniquenames_LD_pruned_bed_region")

### 110193 of 116338 variants removed = 6145 var kept
```

```{r}
###New, pruned file

system("plink --vcf coral_onlyFILTER_bcftools_19Sep2022.vcf --double-id --allow-extra-chr --set-missing-var-ids @:# --extract uniquenames_LD_pruned_bed_region.prune.in --make-bed --out uniquenames_coral_pruneddata") 

```

```{r}

###Pruned output to vcf


system("plink --bfile uniquenames_coral_pruneddata --double-id --allow-extra-chr --set-missing-var-ids @:# --recode vcf --out vcf_uniquenames_coral_pruneddata_final_13Feb2024")

```


```{r}
###Running pcadapt

library(pcadapt)
library(qvalue)


###Let's use bed made before with LD prunning, "region"
```

```{r}

vcf.path = "C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\vcf_uniquenames_coral_pruneddata_final_13Feb2024.vcf" ###unique names

##bed.path = "C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\region.bed"
meta.path = "C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\population.gbs_final_mtorf_FINAL_18Oct2023.csv"

```

```{r}
vcf_pcadapt <- read.vcfR(vcf.path)

vcf_pcadapt
```

```{r}
head(vcf_pcadapt)
```


```{r}

###read new vcf file in, where 4 samples where mtORF = 0 are removed

vcf.path.mtorf = "C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\mtorfCLEAN_vcf_uniquenames_coral_pruneddata_final_13Feb2024.vcf" ###unique names, samples mtorf 0 are removed

genos.clean <- read.pcadapt(vcf.path.mtorf,type=c("vcf"))

head(genos.clean)
```


```{r}
meta <- read.csv(meta.path)
head(meta)

meta$mtorf <- as.factor(meta$mtorf)

meta
```

```{r}

###filter out NAs 

meta_filtered <- meta[!is.na(meta$mtorf), ]

meta_filtered
```


```{r}
x <- pcadapt(input=genos.clean,K=6)
plot(x,option="screeplot")

##Chose top 2 PCs as encompass most variance
```

```{r}

library(ggplot2)

##PC per reef
PCA_reef <- plot(x, option="scores",pop=meta_filtered$reef)

PCA_reef


cols <- c("#FF33FF", 
                "#56B4E9")

##PC per gulf
PCA_gulf <- plot(x,option="scores",pop=meta_filtered$loc, col = cols)


PCA_gulf+theme_bw()

summary(x)

###prop var explained

sing.value <- x$singular.values

sing.value

var_exp <- sing.value^2

var_exp
```

```{r}
PC1 <- x$scores[,1]

PC1
```

```{r}
##PC per mtORF
plot(x,option="scores",pop=meta_filtered$mtorf)
```
```{r}
##PC per gulf & mtORF

cols_orf <- c("orange", 
                "purple")
PCA_orf <- plot(x,option="scores",pop=meta_filtered$mtorf, col = cols_orf) 

PCA_orf
```

```{r}

PCA_orf + facet_wrap(~meta_filtered$loc) + theme_bw() 
```

```{r}
##PC1 vs 3 per reef
plot(x, i = 1, j = 3, option="scores",pop=meta_filtered$reef)

##PC1 vs 3 per gulf
plot(x, i = 1, j = 3, option="scores",pop=meta_filtered$loc)

##PC1 vs 3 per mtORF
plot(x, i = 1, j = 3, option="scores",pop=meta_filtered$mtorf)
```

```{r}

##PC1 vs 4 per reef
plot(x, i = 1, j = 4, option="scores",pop=meta_filtered$reef)

##PC1 vs 4 per gulf
plot(x, i = 1, j = 4, option="scores",pop=meta_filtered$loc)

##PC1 vs 4 per mtORF
plot(x, i = 1, j = 4, option="scores",pop=meta_filtered$mtorf)
```

```{r}
## So while PC1 vs PC3 to some degree recaps PC1 vs PC3, at PC1 vs PC4 patterns of BAD in own cluster dissapear
### What does this mean? PC1 ~ 60% var, while PC2 ~ 10%. PC1 in this case comes to represent perhaps a more normal signal, admixture/neutral/standing genetic variation, while PC>1 show exceptionally different pattern up to PC3.

### Loadings of ~0.6 are significant, here PC1

#### Yet in some cases, e.g. UMAP, higher PCs are more likely to represent subtle, but biologically relevant, sources of heterogeneity – so including them may improve downstream analysis

#### For us, this comes to represent how BAD being different from the other sites is biologically relevant if we see this trend continue to emerge even as increase PC1 > ; likewise PC2 ~ PC3 ~ PC4 so the trend seen not an artifact 

### PC1 = largest eigenvalue which captures the maximum variance data points ; these eigenvalues calculated on the covariance matrix

###  To put it in simpler terms, each PC is a direction in your feature space that's highly relevant to determine what the output is. Each PC is less important than the last, as each eigenvector represents less variance.


```


```{r}
plot(x,option="manhattan")
```

```{r}
qval_full <- qvalue(x$pvalues)$qvalues
outliers_full <- which(qval_full<0.1)
length(outliers_full)

qval_full_0.05 <- qvalue(x$pvalues)$qvalues
outliers_full_0.05 <- which(qval_full_0.05 <0.05)
length(outliers_full_0.05)
```

```{r}
hist(x$pvalues,xlab="p-values", main=NULL, breaks=50)

plot(x, option="stat.distribution")
```



```{r}
##Let's re-run with only 2 PC as encompass most variation

x_PC2 <- pcadapt(input=genos.clean,K=2)

summary(x_PC2)
```

```{r}

##Vis outliers

plot(x_PC2 , option = "manhattan")

```
```{r}
##qqplot

plot(x_PC2, option = "qqplot")

```

```{r}
hist(x_PC2$pvalues,xlab="p-values", main=NULL, breaks=50)

plot(x_PC2, option="stat.distribution")
```

```{r}

###Outliers

qval_full <- qvalue(x_PC2$pvalues)$qvalues
outliers_full <- which(qval_full<0.1)
length(outliers_full)

qval_full_0.05 <- qvalue(x_PC2$pvalues)$qvalues
outliers_full_0.05 <- which(qval_full_0.05 <0.05)
length(outliers_full_0.05)
```

```{r}
vcfR_pruned<-read.vcfR("C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\vcf_pruned_final_13Feb2024.vcf")

vcfR_pruned

```

```{r}

vcf_subset_FDR0.05 <- vcfR_pruned[outliers_full_0.05, ]

head(vcf_subset_FDR0.05)
```

```{r}

write.vcf(vcf_subset_FDR0.05 , "q0.05pcadapt_outliersVCF_TEP_corals_13Feb2024.vcf")
```

```{r}
head(vcf_subset_FDR0.05)
```

```{r}
vcf_subset_FDR0.05 <- read.vcfR("q0.05pcadapt_outliersVCF_TEP_corals_13Feb2024.vcf")
```


```{r}
##Final VCF, without rename to have unique ids; LD pruned and no mtORF = 0 

vcf_prunedLD_uniquenames <- read.vcfR("C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\mtorfCLEAN_vcf_uniquenames_coral_pruneddata_final_13Feb2024.vcf")

head(vcf_prunedLD_uniquenames)

pop.data <- read.table("C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\population.gbs_final_GenAl_20Nov2024.csv", sep = ",", header = TRUE)

head(pop.data)
```


```{r}
library(hierfstat)

```



```{r}
###What about compare across mtORF? 

genind_mtorf <- vcfR2genind(vcf_prunedLD_uniquenames)

pop.data_orf <- read.table("C:\\Users\\vmgly\\Documents\\holobiont_2020-2021\\PCA_19Sep2022\\population.gbs_final_mtorf_FINAL_20Nov2024.csv", sep = ",", header = TRUE)
```

```{r}
pop.data_orf 

pop.data_orf$mtorf <- as.factor(pop.data_orf$mtorf )
```

```{r}
genind_mtorf@pop <- as.factor(pop.data_orf$mtorf)

head(genind_mtorf)
```

```{r}
###check pop

genind_mtorf@pop
```

```{r}
na_samples <- is.na(genind_mtorf@pop)

na_samples
```

```{r}
genid_mtorf_filtered <- genind_mtorf[!na_samples, ]

genid_mtorf_filtered@pop
```

```{r}
library(hierfstat)

basic.stats(genid_mtorf_filtered, diploid = TRUE)

basic.stats
```
